#ifndef POKEFIRERED_NES_PIPELINE_FAIL_SCREEN_H
#define POKEFIRERED_NES_PIPELINE_FAIL_SCREEN_H

enum {
    TEST_EXPECT_8 = 0,
    TEST_EXPECT_16,
    TEST_EXPECT_32
};

void RunEmulationAccuracyTests(void);

#endif //POKEFIRERED_NES_PIPELINE_FAIL_SCREEN_H
