#ifndef GUARD_POKEDEX_AREA_MARKERS_H
#define GUARD_POKEDEX_AREA_MARKERS_H

#define DEXMARKERAREA_PALLET_TOWN           1
#define DEXMARKERAREA_VIRIDIAN_CITY         2
#define DEXMARKERAREA_PEWTER_CITY           3
#define DEXMARKERAREA_CERULEAN_CITY         4
#define DEXMARKERAREA_LAVENDER_TOWN         5
#define DEXMARKERAREA_VERMILION_CITY        6
#define DEXMARKERAREA_CELADON_CITY          7
#define DEXMARKERAREA_FUCHSIA_CITY          8
#define DEXMARKERAREA_CINNABAR_ISLAND       9
#define DEXMARKERAREA_INDIGO_PLATEAU       10
#define DEXMARKERAREA_SAFFRON_CITY         11
#define DEXMARKERAREA_ROUTE_1              12
#define DEXMARKERAREA_ROUTE_2              13
#define DEXMARKERAREA_ROUTE_3              14
#define DEXMARKERAREA_ROUTE_4              15
#define DEXMARKERAREA_ROUTE_5              16
#define DEXMARKERAREA_ROUTE_6              17
#define DEXMARKERAREA_ROUTE_7              18
#define DEXMARKERAREA_ROUTE_8              19
#define DEXMARKERAREA_ROUTE_9              20
#define DEXMARKERAREA_ROUTE_10             21
#define DEXMARKERAREA_ROUTE_11             22
#define DEXMARKERAREA_ROUTE_12             23
#define DEXMARKERAREA_ROUTE_13             24
#define DEXMARKERAREA_ROUTE_14             25
#define DEXMARKERAREA_ROUTE_15             26
#define DEXMARKERAREA_ROUTE_16             27
#define DEXMARKERAREA_ROUTE_17             28
#define DEXMARKERAREA_ROUTE_18             29
#define DEXMARKERAREA_ROUTE_19             30
#define DEXMARKERAREA_ROUTE_20             31
#define DEXMARKERAREA_ROUTE_21             32
#define DEXMARKERAREA_ROUTE_22             33
#define DEXMARKERAREA_ROUTE_23             34
#define DEXMARKERAREA_ROUTE_24             35
#define DEXMARKERAREA_ROUTE_25             36
#define DEXMARKERAREA_VIRIDIAN_FOREST      37
#define DEXMARKERAREA_DIGLETTS_CAVE        38
#define DEXMARKERAREA_MT_MOON              39
#define DEXMARKERAREA_CERULEAN_CAVE        40
#define DEXMARKERAREA_ROCK_TUNNEL          41
#define DEXMARKERAREA_POWER_PLANT          42
#define DEXMARKERAREA_POKEMON_TOWER        43
#define DEXMARKERAREA_SAFARI_ZONE          44
#define DEXMARKERAREA_SEAFOAM_ISLANDS      45
#define DEXMARKERAREA_POKEMON_MANSION      46
#define DEXMARKERAREA_VICTORY_ROAD         47
#define DEXMARKERAREA_ONE_ISLAND           48
#define DEXMARKERAREA_TWO_ISLAND           49
#define DEXMARKERAREA_THREE_ISLAND         50
#define DEXMARKERAREA_FOUR_ISLAND          51
#define DEXMARKERAREA_FIVE_ISLAND          52
#define DEXMARKERAREA_SIX_ISLAND           53
#define DEXMARKERAREA_SEVEN_ISLAND         54
#define DEXMARKERAREA_KINDLE_ROAD          55
#define DEXMARKERAREA_TREASURE_BEACH       56
#define DEXMARKERAREA_CAPE_BRINK           57
#define DEXMARKERAREA_BOND_BRIDGE          58
#define DEXMARKERAREA_THREE_ISLE_PATH      59
#define DEXMARKERAREA_RESORT_GORGEOUS      60
#define DEXMARKERAREA_WATER_LABYRINTH      61
#define DEXMARKERAREA_FIVE_ISLE_MEADOW     62
#define DEXMARKERAREA_MEMORIAL_PILLAR      63
#define DEXMARKERAREA_OUTCAST_ISLAND       64
#define DEXMARKERAREA_GREEN_PATH           65
#define DEXMARKERAREA_WATER_PATH           66
#define DEXMARKERAREA_RUIN_VALLEY          67
#define DEXMARKERAREA_TRAINER_TOWER        68
#define DEXMARKERAREA_CANYON_ENTRANCE      69
#define DEXMARKERAREA_SEVAULT_CANYON       70
#define DEXMARKERAREA_TANOBY_RUINS         71
#define DEXMARKERAREA_MT_EMBER             72
#define DEXMARKERAREA_BERRY_FOREST         73
#define DEXMARKERAREA_ICEFALL_CAVE         74
#define DEXMARKERAREA_LOST_CAVE            75
#define DEXMARKERAREA_ALTERING_CAVE        76
#define DEXMARKERAREA_PATTERN_BUSH         77
#define DEXMARKERAREA_DOTTED_HOLE          78
#define DEXMARKERAREA_TANOBY_CHAMBERS      79

struct PAM_TaskData
{
    struct SubspriteTable subsprites;
    void * buffer;
    u8 unk_0C;
    u8 spr_id;
    u16 tilesTag;
    u16 unk_10;
};

void SetAreaSubsprite(s32 i, s32 whichArea, struct Subsprite * subsprites);
void Dtor_PokedexAreaMarkers(u8 taskId);
u8 Ctor_PokedexAreaMarkers(u16 species, u16 tilesTag, u8 palIdx, u8 y);
u8 PokedexAreaMarkers_Any(u8 taskId);

#endif //GUARD_POKEDEX_AREA_MARKERS_H
