name: Release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi libcapstone-dev
          git clone https://github.com/PikalaxALT/universal-pokemon-randomizer UPR -b fr_support_2slot
          cd UPR
          curl https://versaweb.dl.sourceforge.net/project/launch4j/launch4j-3/3.14/launch4j-3.14-linux-x64.tgz | tar -xzv

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8

      - name: Install agbcc
        run: |
          git clone https://github.com/pret/agbcc.git
          cd agbcc
          ./build.sh
          ./install.sh ../

      - name: Build
        run: |
          make -j${nproc} rando UPRDIR=UPR

      - name: Package Release
        run: |
          read addr size type name <<< $(nm -SBgn pokefirered-speedchoice.elf | grep -w gSpeedchoiceVersion)
          verstr=$(dd if=pokefirered-speedchoice.gba bs=1 skip=$((0x${addr} & 0xFFFFFF)) count=$((0x${size} - 1)))
          export relname=pokemon-firered-speedchoice-${verstr}-plus-randomizer
          mkdir ${relname}
          cp -r pokefirered-speedchoice.gba UPR/build/$(date '+%Y%m%d')/* ${relname}/
          zip -r ${relname}.zip ${relname}/

      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: pokemon-firered-speedchoice-*-plus-randomizer.zip
